ksql> CREATE TABLE hassana
  (_SOURCE_REALTIME_TIMESTAMP VARCHAR,
   _REALTIME_TIMESTAMP VARCHAR,
   _CAP_EFFECTIVE VARCHAR,
   MESSAGE VARCHAR,
   SYSLOG_TIMESTAMP VARCHAR)
  WITH (KAFKA_TOPIC='topic-journald',
        PARTITIONS=1,
        VALUE_FORMAT='json'
  );
