CREATE STREAM djib12

(viewtime BIGINT,
   USER_ID VARCHAR,
   SESSION_ID VARCHAR,
   REALTIME_TIMESTAMP VARCHAR)
WITH (
    KEY='USER_ID',
    VALUE_FORMAT='JSON',
    KAFKA_TOPIC='topic-journald'
  );
