CREATE TABLE lago
  (_SOURCE_REALTIME_TIMESTAMP VARCHAR,
    _SYSTEMD_UNIT VARCHAR,
   __MONOTONIC_TIMESTAMP VARCHAR,
   SYSLOG_TIMESTAMP VARCHAR)
  WITH (KAFKA_TOPIC='topic-journald',
        PARTITIONS=1,
        VALUE_FORMAT='json'
  );
        
