CREATE TABLE lago
  (SYSLOG_FACILITY VARCHAR,
   SYSLOG_IDENTIFIER VARCHAR,
   SYSLOG_PID VARCHAR,
   SYSLOG_TIMESTAMP VARCHAR)
  WITH (KAFKA_TOPIC='topic-journald',
        PARTITIONS=1,
        VALUE_FORMAT='json'
  );
        
